version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    # image: php:8.0-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    depends_on:
        - db
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=YKfRRfvzwmW79pF
      - MYSQL_DATABASE=php-docker
      - MYSQL_USER=felhi
      - MYSQL_PASSWORD=WWqAaRy4TFrV
    # volumes:
      # - ../mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
        - db
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 300M
    ports:
        - '8003:80'